import mongoose from "mongoose";
import { loadType } from "mongoose-currency";


const Schema = mongoose.Schema;
loadType(mongoose);

const PortfolioSchema = new Schema(
  {
    ticker: String, 
    portfolio: [{
        company_name: String,
        currency: String,
        exchange: String,
        last_price: Number,
        change: Number,
        chg_percent: String,
        market_time: String,
        volume: String,
        avg_vol_m3: String,
        avg_vol_d10: String,
        day_range: String,
        day_chart: String,
        bid: Number,
        bid_size: Number,
        ask: Number,
        ask_size: Number,
        prev_close: Number,
        shares: String,
        open: Number,
        high: Number,
        low: Number,
        wk_high52: Number,
        wk_low52: Number,
        wk_high_chg52: Number,
        wk_high_chg_percent52: String,
        wk_low_chg5: String,
        wk_low_chg_percent52: String,
        shares_out: String,
        short_ratio: String,
        wk_range52: String,
        pre_mkt_time: String,
        pre_mkt_price: String,
        pre_mkt_chg: String,
        pre_mkt_chg_percent: String,
        post_mkt_time: String,
        post_mkt_price: Number,
        post_mkt_chg: Number,
        post_mkt_chg_percent: String,
        eps_ttm: Number,
        trailing_p_e: Number,
        forward_p_e: String,
        div_payment_date: String,
        ex_div_date: String,
        div_share: String,
        forward_annual_div_rate: String,
        forward_annual_div_yield: String,
        trailing_annual_div_rate: String,
        trailing_annual_div_yield: String,
        market_cap: String,
        book_val: String,
        price_book: String,
        price_sales: String,
        ebitda: String,
        earnings_date: String,
        yr_target_est1: String,
        eps_est_next_year: String,
        eps_current_year: String,
        peg_ratio__yr_expected5: String,
        dma50: Number,
        dma_chg50: Number,
        dma_chg_percent50: String,
        dma200: Number,
        dma_chg200: Number,
        dma_chg_percent200: String,
        trade_date: String,
        high_limit: String,
        low_limit: String,
        cost_share: String,
        market_value: String,
        total_chg: String,
        total_chg_percent: String,
        day_chg: String,
        day_chg_percent: String,
        notes: String,
        no_of_lots: String,
        annualised_gain: String,
        extra_column1: String,
        extra_column2: String
    }],
  },
  { timestamps: true, toJSON: { getters: true } }
);

const Portfolio = mongoose.model("Portfolio", PortfolioSchema);

export default Portfolio;